const RecurringTransaction = require("../models/RecurringTransaction");
const Transaction = require("../models/transaction");

const generateRecurringTransactions = async () => {
  const today = new Date();
  const weekday = today.getDay();       // 0 = Sunday
  const dateOfMonth = today.getDate();  // 1–31

  const rules = await RecurringTransaction.find({
    startDate: { $lte: today },
    $or: [
      { endDate: null },
      { endDate: { $gte: today } }
    ]
  });

  for (const rule of rules) {
    const { frequency, day, lastGenerated, userId, title, amount, type } = rule;

    const alreadyInserted = lastGenerated &&
      new Date(lastGenerated).toDateString() === today.toDateString();

    const isTodayMatch = frequency === "monthly"
      ? dateOfMonth === day
      : frequency === "weekly"
        ? weekday === (day % 7)
        : false;

    if (isTodayMatch && !alreadyInserted) {
      await Transaction.create({
        userId,
        title,
        amount,
        type,
        description: "Auto-posted from recurring rule",
        date: today,
        isAutoGenerated: true
      });

      rule.lastGenerated = today;
      await rule.save();
    }
  }
};

module.exports = generateRecurringTransactions;
